#compose.yaml sirve para describir qué contenedores forman la aplicación y cómo se levantan juntos.
services:
# * services: → lista de servicios/contenedores que Compose gestionará.
# * opswatch: → nombre lógico de nuestro primer servicio.
  opswatch:
    # Para construir el contenedor de opswatch, usa como contexto de construcción el directorio actual (.).
    build: .
    container_name: opswatch
  
  # postgres: → nombre lógico de nuestro segundo servicio.
  postgres:
    image: postgres:18
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
    # pg_isready es una utilidad de PostgreSQL que pregunta básicamente:  «¿PostgreSQL está disponible para aceptar conexiones?»
      test: ['CMD-SHELL','pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    



volumes:
  postgres_data: